// Code generated by sqlc. DO NOT EDIT.
// source: cuenta.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO cuenta (
  propietario,
  tope,
  divisa
) VALUES (
  $1, $2, $3
)
RETURNING id, propietario, tope, divisa, created_at
`

type CreateAccountParams struct {
	Propietario string `json:"propietario"`
	Tope        int64  `json:"tope"`
	Divisa      string `json:"divisa"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Cuentum, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Propietario, arg.Tope, arg.Divisa)
	var i Cuentum
	err := row.Scan(
		&i.ID,
		&i.Propietario,
		&i.Tope,
		&i.Divisa,
		&i.CreatedAt,
	)
	return i, err
}
