// Code generated by sqlc. DO NOT EDIT.
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO ingreso (
  cuenta_id,
  monto
) VALUES (
  $1, $2
) RETURNING id, cuenta_id, monto, created_at
`

type CreateEntryParams struct {
	CuentaID int64 `json:"cuenta_id"`
	Monto    int64 `json:"monto"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Ingreso, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.CuentaID, arg.Monto)
	var i Ingreso
	err := row.Scan(
		&i.ID,
		&i.CuentaID,
		&i.Monto,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, cuenta_id, monto, created_at FROM ingreso
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Ingreso, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Ingreso
	err := row.Scan(
		&i.ID,
		&i.CuentaID,
		&i.Monto,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, cuenta_id, monto, created_at FROM ingreso
WHERE cuenta_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	CuentaID int64 `json:"cuenta_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Ingreso, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.CuentaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingreso
	for rows.Next() {
		var i Ingreso
		if err := rows.Scan(
			&i.ID,
			&i.CuentaID,
			&i.Monto,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
