// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Cuentum struct {
	ID          int64     `json:"id"`
	Propietario string    `json:"propietario"`
	Tope        int64     `json:"tope"`
	Divisa      string    `json:"divisa"`
	CreatedAt   time.Time `json:"created_at"`
}

type Ingreso struct {
	ID       int64 `json:"id"`
	CuentaID int64 `json:"cuenta_id"`
	// Puede ser negativo o positivo
	Monto     int64     `json:"monto"`
	CreatedAt time.Time `json:"created_at"`
}

type Transferencium struct {
	ID           int64 `json:"id"`
	FromCuentaID int64 `json:"from_cuenta_id"`
	ToCuentaID   int64 `json:"to_cuenta_id"`
	// Debe ser positivo
	Monto     int64     `json:"monto"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	Password          string    `json:"password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
